// Generated by scripts/process-photos.mjs. Do not edit by hand.
export type PhotoCategory = "exterior" | "interior" | "workshop" | "company" | "people"

export type PhotoEntry = {
  id: string
  category: PhotoCategory
  src: string
  width: number
  height: number
}

export const photoManifest: readonly PhotoEntry[] = [
  {
    "id": "exterior-7727",
    "category": "exterior",
    "src": "/photos/exterior/7727.webp",
    "width": 1920,
    "height": 1080
  },
  {
    "id": "exterior-7724",
    "category": "exterior",
    "src": "/photos/exterior/7724.webp",
    "width": 1920,
    "height": 1080
  },
  {
    "id": "exterior-7725",
    "category": "exterior",
    "src": "/photos/exterior/7725.webp",
    "width": 1920,
    "height": 1080
  },
  {
    "id": "exterior-0417",
    "category": "exterior",
    "src": "/photos/exterior/0417.webp",
    "width": 1920,
    "height": 1280
  },
  {
    "id": "exterior-0418",
    "category": "exterior",
    "src": "/photos/exterior/0418.webp",
    "width": 1920,
    "height": 1280
  },
  {
    "id": "exterior-0422",
    "category": "exterior",
    "src": "/photos/exterior/0422.webp",
    "width": 1920,
    "height": 1280
  },
  {
    "id": "exterior-0427",
    "category": "exterior",
    "src": "/photos/exterior/0427.webp",
    "width": 2528,
    "height": 1684
  },
  {
    "id": "exterior-0441",
    "category": "exterior",
    "src": "/photos/exterior/0441.webp",
    "width": 1920,
    "height": 1280
  },
  {
    "id": "exterior-0431",
    "category": "exterior",
    "src": "/photos/exterior/0431.webp",
    "width": 1920,
    "height": 1280
  },
  {
    "id": "exterior-0436",
    "category": "exterior",
    "src": "/photos/exterior/0436.webp",
    "width": 1920,
    "height": 1280
  },
  {
    "id": "interior-0212",
    "category": "interior",
    "src": "/photos/interior/0212.webp",
    "width": 1920,
    "height": 1280
  },
  {
    "id": "interior-0222",
    "category": "interior",
    "src": "/photos/interior/0222.webp",
    "width": 1920,
    "height": 1280
  },
  {
    "id": "interior-0213",
    "category": "interior",
    "src": "/photos/interior/0213.webp",
    "width": 1920,
    "height": 1280
  },
  {
    "id": "interior-0217",
    "category": "interior",
    "src": "/photos/interior/0217.webp",
    "width": 1920,
    "height": 1280
  },
  {
    "id": "interior-0231",
    "category": "interior",
    "src": "/photos/interior/0231.webp",
    "width": 1920,
    "height": 1280
  },
  {
    "id": "interior-0236",
    "category": "interior",
    "src": "/photos/interior/0236.webp",
    "width": 1920,
    "height": 1280
  },
  {
    "id": "interior-0225",
    "category": "interior",
    "src": "/photos/interior/0225.webp",
    "width": 1920,
    "height": 1280
  },
  {
    "id": "interior-0269",
    "category": "interior",
    "src": "/photos/interior/0269.webp",
    "width": 1920,
    "height": 1280
  },
  {
    "id": "interior-0274",
    "category": "interior",
    "src": "/photos/interior/0274.webp",
    "width": 1920,
    "height": 1280
  },
  {
    "id": "interior-0283",
    "category": "interior",
    "src": "/photos/interior/0283.webp",
    "width": 1920,
    "height": 1280
  },
  {
    "id": "interior-0301",
    "category": "interior",
    "src": "/photos/interior/0301.webp",
    "width": 1920,
    "height": 1280
  },
  {
    "id": "interior-0394",
    "category": "interior",
    "src": "/photos/interior/0394.webp",
    "width": 1920,
    "height": 1280
  },
  {
    "id": "interior-0396",
    "category": "interior",
    "src": "/photos/interior/0396.webp",
    "width": 1920,
    "height": 1280
  },
  {
    "id": "workshop-0123",
    "category": "workshop",
    "src": "/photos/workshop/0123.webp",
    "width": 1920,
    "height": 1280
  },
  {
    "id": "workshop-0126",
    "category": "workshop",
    "src": "/photos/workshop/0126.webp",
    "width": 1920,
    "height": 1280
  },
  {
    "id": "workshop-0146",
    "category": "workshop",
    "src": "/photos/workshop/0146.webp",
    "width": 1920,
    "height": 1280
  },
  {
    "id": "workshop-0153",
    "category": "workshop",
    "src": "/photos/workshop/0153.webp",
    "width": 1920,
    "height": 1280
  },
  {
    "id": "workshop-0168",
    "category": "workshop",
    "src": "/photos/workshop/0168.webp",
    "width": 1920,
    "height": 1280
  },
  {
    "id": "workshop-0205",
    "category": "workshop",
    "src": "/photos/workshop/0205.webp",
    "width": 1920,
    "height": 1280
  },
  {
    "id": "workshop-0371",
    "category": "workshop",
    "src": "/photos/workshop/0371.webp",
    "width": 1920,
    "height": 1280
  },
  {
    "id": "workshop-0342",
    "category": "workshop",
    "src": "/photos/workshop/0342.webp",
    "width": 1920,
    "height": 1280
  },
  {
    "id": "workshop-0331",
    "category": "workshop",
    "src": "/photos/workshop/0331.webp",
    "width": 1920,
    "height": 1280
  },
  {
    "id": "workshop-0334",
    "category": "workshop",
    "src": "/photos/workshop/0334.webp",
    "width": 1920,
    "height": 1280
  },
  {
    "id": "workshop-0358",
    "category": "workshop",
    "src": "/photos/workshop/0358.webp",
    "width": 1920,
    "height": 1280
  },
  {
    "id": "workshop-0362",
    "category": "workshop",
    "src": "/photos/workshop/0362.webp",
    "width": 1920,
    "height": 1280
  },
  {
    "id": "workshop-0180",
    "category": "workshop",
    "src": "/photos/workshop/0180.webp",
    "width": 1920,
    "height": 1280
  },
  {
    "id": "company-0098",
    "category": "company",
    "src": "/photos/company/0098.webp",
    "width": 1920,
    "height": 1280
  },
  {
    "id": "company-0108",
    "category": "company",
    "src": "/photos/company/0108.webp",
    "width": 1920,
    "height": 1280
  },
  {
    "id": "company-0113",
    "category": "company",
    "src": "/photos/company/0113.webp",
    "width": 1920,
    "height": 1280
  },
  {
    "id": "company-0444",
    "category": "company",
    "src": "/photos/company/0444.webp",
    "width": 1920,
    "height": 1280
  },
  {
    "id": "company-0449",
    "category": "company",
    "src": "/photos/company/0449.webp",
    "width": 1920,
    "height": 1280
  },
  {
    "id": "company-0454",
    "category": "company",
    "src": "/photos/company/0454.webp",
    "width": 1920,
    "height": 1280
  },
  {
    "id": "people-0457",
    "category": "people",
    "src": "/photos/people/0457.webp",
    "width": 1920,
    "height": 1280
  },
  {
    "id": "people-0463",
    "category": "people",
    "src": "/photos/people/0463.webp",
    "width": 1920,
    "height": 1280
  },
  {
    "id": "people-0467",
    "category": "people",
    "src": "/photos/people/0467.webp",
    "width": 1920,
    "height": 1280
  },
  {
    "id": "people-0475",
    "category": "people",
    "src": "/photos/people/0475.webp",
    "width": 1920,
    "height": 1280
  },
  {
    "id": "people-0478",
    "category": "people",
    "src": "/photos/people/0478.webp",
    "width": 1920,
    "height": 1280
  },
  {
    "id": "people-0486",
    "category": "people",
    "src": "/photos/people/0486.webp",
    "width": 1920,
    "height": 1280
  },
  {
    "id": "people-0496",
    "category": "people",
    "src": "/photos/people/0496.webp",
    "width": 1920,
    "height": 1280
  },
  {
    "id": "people-0505",
    "category": "people",
    "src": "/photos/people/0505.webp",
    "width": 1920,
    "height": 1280
  }
]
