import type { L10n } from "./quoteWizardConfig"
import type { StepId } from "./quoteWizardTypes"

export const COPY = {
  stepOf: (c: number, t: number, name: string): L10n => ({
    en: `Step ${c} of ${t}: ${name}`,
    ar: `الخطوة ${c} من ${t}: ${name}`,
  }),
  stepCount: (c: number, t: number): L10n => ({
    en: `${c} of ${t}`,
    ar: `${c} من ${t}`,
  }),
  stepNames: {
    customer: { en: "Audience", ar: "الجهة" },
    service: { en: "Service", ar: "الخدمة" },
    route: { en: "Route", ar: "المسار" },
    passengers: { en: "Travellers", ar: "المسافرون" },
    vehicle: { en: "Fleet", ar: "الأسطول" },
    extras: { en: "Notes", ar: "ملاحظات" },
    contact: { en: "Contact", ar: "التواصل" },
    review: { en: "Review", ar: "المراجعة" },
  } satisfies Record<StepId, L10n>,
  titles: {
    customer: { en: "Who is this request for?", ar: "لمن هذا الطلب؟" },
    service: { en: "What do you need?", ar: "ماذا تحتاج؟" },
    route: { en: "Where and when?", ar: "من أين إلى أين، ومتى؟" },
    passengers: { en: "Who is travelling?", ar: "من المسافرون؟" },
    vehicle: { en: "Choose your buses", ar: "اختر الحافلات" },
    extras: { en: "Anything else we should know?", ar: "هل هناك أي شيء آخر نحتاج أن نعرفه؟" },
    contact: { en: "How can we reach you?", ar: "كيف نتواصل معك؟" },
    review: { en: "Review and send", ar: "راجع وأرسل" },
  } satisfies Record<StepId, L10n>,
  next: { en: "Continue", ar: "متابعة" },
  back: { en: "Back", ar: "رجوع" },
  submit: { en: "Send request", ar: "إرسال الطلب" },
  sending: { en: "Sending…", ar: "جارٍ الإرسال…" },
  edit: { en: "Edit", ar: "تعديل" },
  error: {
    en: "Something went wrong. Please try again or contact us on WhatsApp.",
    ar: "حدث خطأ ما. حاول مرة أخرى أو تواصل معنا عبر واتساب.",
  },
  fields: {
    name: { en: "Full name", ar: "الاسم الكامل" },
    organization: { en: "Organization / mission", ar: "اسم الجهة" },
    phone: { en: "Phone / WhatsApp", ar: "الجوال / واتساب" },
    email: { en: "Email (optional)", ar: "البريد الإلكتروني (اختياري)" },
    pickup: { en: "From (city / exact location)", ar: "من (المدينة / الموقع)" },
    destination: { en: "To", ar: "إلى" },
    stops: { en: "Stops (optional)", ar: "نقاط توقف (اختياري)" },
    from: { en: "From", ar: "من" },
    to: { en: "To", ar: "إلى" },
    arrival: { en: "Arrive at", ar: "الوصول إلى" },
    departure: { en: "Depart from", ar: "المغادرة من" },
    date: { en: "Date", ar: "التاريخ" },
    time: { en: "Time", ar: "الوقت" },
    returnDate: { en: "Return / end date", ar: "تاريخ العودة / النهاية" },
    returnDateOptional: {
      en: "Return / end date (optional)",
      ar: "تاريخ العودة / النهاية (اختياري)",
    },
    waiting: { en: "Waiting hours (optional)", ar: "ساعات الانتظار (اختياري)" },
    passengers: { en: "Number of passengers", ar: "عدد الركاب" },
    luggage: { en: "Luggage (optional)", ar: "الأمتعة (اختياري)" },
    accessibility: { en: "Accessibility needs (optional)", ar: "احتياجات خاصة (اختياري)" },
    busCount: { en: "Number of buses", ar: "عدد الحافلات" },
    notes: { en: "Anything else we should know?", ar: "هل هناك أي شيء آخر نحتاج أن نعرفه؟" },
  },
  addLeg: { en: "Add another trip", ar: "إضافة رحلة أخرى" },
  removeLeg: { en: "Remove this trip", ar: "حذف هذه الرحلة" },
  legTitle: (n: number): L10n => ({ en: `Trip ${n}`, ar: `الرحلة ${n}` }),
  pickPlace: { en: "Choose a location", ar: "اختر الموقع" },
  pickDate: { en: "Choose a date", ar: "اختر التاريخ" },
  pickTime: { en: "Choose a time", ar: "اختر الوقت" },
  consent: {
    en: "I agree to share my details with the sales team under the privacy policy. A request is not a confirmed booking until an official offer is issued.",
    ar: "أوافق على مشاركة بياناتي مع فريق المبيعات وفق سياسة الخصوصية. الطلب ليس حجزاً مؤكداً حتى يصدر عرض رسمي.",
  },
  errors: {
    choose: { en: "Please choose an option to continue.", ar: "الرجاء اختيار خيار للمتابعة." },
    name: { en: "Please enter your full name.", ar: "الرجاء إدخال الاسم الكامل." },
    organization: { en: "Please enter the organization name.", ar: "الرجاء إدخال اسم الجهة." },
    phone: { en: "Please enter a number we can reach you on.", ar: "الرجاء إدخال رقم للتواصل." },
    email: { en: "That email doesn't look right.", ar: "البريد الإلكتروني غير صحيح." },
    place: { en: "Please enter the place.", ar: "الرجاء إدخال الموقع." },
    samePlace: { en: "Start and end must be different.", ar: "نقطة البداية والنهاية يجب أن تختلفا." },
    date: { en: "Please choose a date.", ar: "الرجاء اختيار التاريخ." },
    time: { en: "Please choose a time.", ar: "الرجاء اختيار الوقت." },
    returnDate: { en: "Please choose the return date.", ar: "الرجاء اختيار تاريخ العودة." },
    returnBefore: { en: "Return can't be before departure.", ar: "تاريخ العودة قبل المغادرة." },
    passengers: { en: "Please enter the number of passengers.", ar: "الرجاء إدخال عدد الركاب." },
    buses: { en: "Please enter the number of buses.", ar: "الرجاء إدخال عدد الحافلات." },
    consent: { en: "Please tick the box to agree before sending.", ar: "الرجاء الموافقة قبل الإرسال." },
  },
  done: {
    eyebrow: { en: "Request received", ar: "تم استلام الطلب" },
    title: { en: "Thank you, your request is in.", ar: "شكراً لك، وصلنا طلبك." },
    number: { en: "Request number", ar: "رقم الطلب" },
    eta: (h: number): L10n => ({
      en: `Our team will respond within about ${h} hours via your phone or WhatsApp.`,
      ar: `سيرد عليك فريقنا خلال ${h} ساعة تقريباً عبر الجوال أو واتساب.`,
    }),
    note: {
      en: "This is not a booking confirmation. Prices and availability are confirmed only in an official offer.",
      ar: "هذا ليس تأكيد حجز. الأسعار والتوافر تؤكد فقط في العرض الرسمي.",
    },
    another: { en: "Start another request", ar: "طلب جديد" },
  },
  summary: {
    who: { en: "Customer", ar: "العميل" },
    service: { en: "Service", ar: "الخدمة" },
    route: { en: "Route", ar: "المسار" },
    leg: (n: number): L10n => ({ en: `Trip ${n}`, ar: `الرحلة ${n}` }),
    passengers: { en: "Passengers", ar: "الركاب" },
    vehicle: { en: "Buses", ar: "الحافلات" },
    extras: { en: "Notes", ar: "ملاحظات" },
    contact: { en: "Contact", ar: "التواصل" },
  },
}
